stages:
  - test
  - build

test:
  stage: test
  image: golang:1.17
  script:
   - go test .
  tags:
   - dr0zd

build:
  stage: build
  image: docker:latest
  script:
   - docker build .
  tags:
   -  dr0zd
